Repository orcwg/cra-hub, pull requests merged in 2025-04, with the labels that each got.

#191 Properly acknowledge FAQ contributors
  faq.md
Labels: FAQ

#188 Clarify difference between harmonised and referenced standard
  faq.md
Labels: FAQ, Standards

#173 Adding a question if a project can be without a steward
  faq.md
Labels: FAQ, Open source project

#202 recital 5: reference the Art 32(5) exception for FOSS
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#204 network management systems: provide examples of current scope of text
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#215 Suggestion to rename annex table column
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#205 recital 2: proposals
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#214 Suggestion for SIEM
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#177 Propose changes to the definition of browsers
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#201 recital 4: state general principle behind SOAR example
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#206 recital 3: proposed a small change
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#210 Suggestion for Password Managers
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#209 Suggestions for Identity Managements category
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#212 Suggestions for Boot Managers
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#203 PKI: raise visibility of inclusion of relying party side of PKI's
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#211 Suggestions for Anti-Malicious Software
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#213 Suggestions for Operating Systems
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products

#219 Suggestions for Container Runtimes only (Hypervisors are in a different PR)
  product-definitions/input-to-draft-regulation.md
Labels: Critical and Important Products
